### ISSUE TITLE
[low priority] Config file - Keypair

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#10]
I want my relay to be connected to my keypair so that HTTPS queries to the main endpoint will list me as the relay admin.

There doesn't seem to be any basic way to set the keypair, would it be reasonable to create a plaintext config file to specify them (and maybe the bootstrap list as well so that we don't have to rebuild the app every time we add or remove a relay?)

**Comment by ZenenTreadwell** [comment]
marked as low-priority as I found a pretty easy way to make a moderator list which didn't require this

**Comment by AutonomousOrganization** [comment]
For now you can your pubkey (and everything nip11) directly by editing here : https://github.com/AutonomousOrganization/futr2/blob/2f4acf15a94e4cd798905d99b95d0b0b6f48db6c/app/Main.hs#L105

I think the relay is basically done so it is time to think about making a 'just a relay' release and what the configuration setup and relay control will look like. It's working as a relay aggregator atm because I was testing and experimenting with the client tool abstractions. When starting on this it seemed reasonable to me that a client should be a relay / the distinction is moot. It's still in a halfway place where several tables (identities, relays) are client things. Strictly a client should be managing / connecting directly to its relays and a relay should only get events created by client connections. 

One idea I had is config events (kind -1?) that make adjustments via the nostr protocol itself?

**Comment by ZenenTreadwell** [comment]
Regarding the "every client is a relay", I've actually been doing some work on this front. The repository isn't really functional yet / most of my dev capacity has been focused on a client that implements this system rather than building out the system itself, but [Solar](https://github.com/Credenso/solar) is intended (among other things) to leverage Hypercore protocol to save event-logs in the indexedDB and then seed them over a DHT. 

The idea is that each member keeps their own personal events log on their system and when people "follow" that member, they actually replicate the events log (Hypercore) and associated Hyperdrive (containing static profile resources) and become seeders for the associated data. It adds a fully P2P layer to the Nostr system and allows for client-side persistence (via random-access-indexeddb) so that people aren't constantly redownloading the same data.

There's a lot more to this idea but it's only half-baked at the moment. It would be nice to rewrite it in a better language than Javascript but that's what the main implementation of Hypercore is in. 

Regarding aggregation - I'm happy with it having the functionality to syndicate with other relays. In practice I've been disabling the bootstrap list, but I like that it has the capacity to propagate data from other relays once other Solar stations are active. 

---

I like the idea of kind -1 config events in the sense that "everything is a nostr event", but I think that they would be best as a single replaceable event (like a user metadata event) since consistently reapplying a series of configurations would probably get taxing. On that note... would it be possible for the relay itself to have a metadata event that holds its config information?

**Comment by AutonomousOrganization** [comment]
DHT? indexedDB? Hypercore protocol? event-logs? What problem is being addressed by all that complexity? (Don't try to explain it to me). Nostr is great because it addresses big problems: validity, integrity, distributey(?), & identity while minimizing complexity.

The problem with keeping the current aggregation is that it is a lie. It is pulling events from other servers so a client can see them, but its replies will not propagate out to where it will be actually seen.

**Comment by ZenenTreadwell** [comment]
I think that what you're looking for is a two-way reciprocal relationship between relays. I'm pretty sure you've already built up a lot of the scaffolding and at this point it's a matter of putting the pieces together. 

I want to support and I'm willing to put the time in to keep learning Haskell, but my brain is still adjusting to functional programming so it's going to take time.

**Comment by ZenenTreadwell** [comment]
As for the first question, I'm trying to address content distribution and data persistence. I know the current implementation isn't great, so let me know if you have any ideas for a more integrated way to do it. NIP-94 has options for torrent hashes but I haven't invested into figuring out how I might make them work.

**Comment by AutonomousOrganization** [comment]
I'm pretty sure content distribution and data persistence are solved by relay propagation.

**Comment by ZenenTreadwell** [comment]
In the case of one PC serving videos or pages of photos to multiple clients, I feel like there's the potential for it to easily get overwhelmed. 

That said - I haven't actually run into these problems yet. Thanks for the sanity check, I'll keep the v1 release simple and will have the code published soon.

**Comment by AutonomousOrganization** [comment]
Out on a branch but went with the seemingly standard ~/.futr/ directory and futr.conf file : 
```
name = x
contact = x 
description = x 
pubkey = x
```

**Comment by ZenenTreadwell** [comment]
Great! It's only the pubkey though, does this mean that the actual key used for the relay is still randomly generated and stored, and the pubkey setting is only outward facing?
