### ISSUE TITLE
GUI is hanging

### ISSUE THREAD

**Issue by ZenenTreadwell** [AutonomousOrganization/futr2#13]
Loading the futr app on my computer in its current form works for a moment (i can enter text into the search box) and then hangs indefinitely.  It was working as of commit `ac79cd8`, and has since stopped.

also... there's a disproportionately high amount of anime girl pics coming from some of the relays... I'm not sure which ones but it's not my favorite to see

**Comment by AutonomousOrganization** [comment]
I was assembling the building blocks / testing if things worked / exploring the monomer api more than anything so far and think I am going to throw out this picture carousel concept. 

I think the reason it is hanging is simply because I naively attached the monomer Producer to the database eventfeed, then subscribed to every relay in the world. So at some point it just gets more updates than it can handle. Although it freezes now, signs point to this being very performant if the event producer is rational / user caused. 

Notes on things I have figured out:

When you display the same image multiple times using `image` the fetch from the URI seems to happen over and over. Futr.Imgs now has some functions that fetch the resource (using library req) and display using imageMem. I think handling the image bytestring as part of the monomer state is going to work. 

The layout api for monomer is box, hstack, vstack, hsplit, vsplit. The spacing is a little weird as it stretches to fill the space. Can get the image to be a fixed size by setting the width on a box then putting fitWidth on the image inside the box. 

I attached the textfield to a custom top level state and it sort of seemed to work, but I am pretty sure that I'm missing something in how inputs are supposed to work.

I used a regular expressions library to parse stuff out of the event (living in Nostr.Kinds). Confirmed the links / tags getting parsed out. Think there may be some other things that can parse out.

Anyway, yes I know everything is broken but I pushed because getting the regex / req stuff working were wins. 

Currently the relay / db have no concept of which relay originated events. So I need to make some db changes to be able to display the originating relay / pubkey with the events so you can follow or unfollow is obvious. Design to usefully express information coming in from so many relays is hard, I'm not really sure where to start.

**Comment by ZenenTreadwell** [comment]
Re: event origination, in the framework I'm working with, I request all of my events from a single relay (my own) and they are returned as a list. I then process the events in that list with a mechanism comparable to the ao-3 mutator. My idea for multiple relays is to make individual requests to each address and then rely on the mutator to merge them all into one cohesive view. Depending on how efficient I need origination to be, I would either append the relay of origin to each event as it's being processed (events are read-only, so once they're verified you can mutate them as you wish for your own purposes), or check for membership of the event in the individual relay lists. Not sure how much that would apply here, though.

I've got no problems with the GUI being broken so long as the relay remains stable. I'm hedging my bets on this as a platform and I have faith in what you're doing. I'm just trying to help the only way I feel capable of right now, which is intermittently testing the software and reporting anything that seems wrong.

I'm curious - has that textfield been given an implementation yet? I'd like to spend some time talking about your plans for what you're building here, if you have the bandwidth for it.

**Comment by AutonomousOrganization** [comment]
hmm speaking of relay stability... :blush:, I just made some changes to the db tables that won't migrate (changes that could lose data like removing deprecated fields or changing types (ByteString -> Text) are not backwards compatible). I think these changes are worthy for consistency/simplicity. . . last time. New fields and new tables which should auto-migrate, but seems complete/ don't think will need to.

The tests cover a lot, think it is unlikely the relay breaks without getting noticed

**Comment by AutonomousOrganization** [comment]
For origination I added a table that the pool updates separately that references relay table and event table. It also creates an entry when I receive an Event I already have. Turns out A LOT of relays are mirroring damos, that's definitely one criteria for turning them off. 

Sure we can chat about where this is heading, I certainly don't know
